kind = "web"
previewPath = "/"
title = "Desire Eyotaru Portfolio"
version = "1.0.0"
id = "artifacts/portfolio"

[[services]]
localPort = 3000
name = "web"
paths = ["/"]

[services.env]
PORT = "3000"
BASE_PATH = "/"

[services.development]
run = "pnpm --filter @workspace/portfolio run dev"
